import { db } from "./db";
import { sql } from "drizzle-orm";

export async function runMigrations() {
  console.log("Running database migrations...");

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS states (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      abbreviation VARCHAR(2) NOT NULL UNIQUE,
      slug TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL,
      meta_title TEXT,
      meta_description TEXT,
      hero_image_url TEXT,
      agency_name TEXT NOT NULL,
      agency_abbreviation TEXT,
      minimum_age INTEGER,
      minimum_age_online_only INTEGER,
      field_day_required BOOLEAN NOT NULL DEFAULT true,
      field_day_details TEXT,
      course_url TEXT,
      course_price TEXT,
      additional_requirements TEXT,
      important_notes TEXT,
      is_active BOOLEAN NOT NULL DEFAULT true
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS articles (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT NOT NULL UNIQUE,
      excerpt TEXT NOT NULL,
      content TEXT NOT NULL,
      meta_title TEXT,
      meta_description TEXT,
      cover_image_url TEXT,
      author_id VARCHAR,
      is_published BOOLEAN NOT NULL DEFAULT false,
      published_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS resources (
      id SERIAL PRIMARY KEY,
      state_id INTEGER,
      title TEXT NOT NULL,
      url TEXT NOT NULL,
      description TEXT,
      resource_type TEXT NOT NULL DEFAULT 'official_state_page',
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMP NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    )
  `);

  // Migration v2: Update all state data with accurate requirements, agencies, and URLs
  console.log("Running state data accuracy updates (v2)...");

  const stateUpdates = [
    { slug: "alabama", description: "Online boater education course approved by NASBLA. Alabama requires boater education for operators age 12+ on motorboats with 15+ hp.", agencyName: "Alabama Law Enforcement Agency - Marine Patrol Division", agencyAbbreviation: "ALEA", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://www.alea.gov/dps/marine-patrol/boating-education-and-operator-certificationlicense", importantNotes: "Required for operators age 12+ on motorboats with 15+ hp. Operators ages 12-13 must have adult supervision.", fieldDayDetails: null },
    { slug: "alaska", description: "Alaska has no mandatory boating safety education requirement, though courses are recommended for all boaters.", agencyName: "Alaska Department of Natural Resources - Office of Boating Safety", agencyAbbreviation: "DNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://dnr.alaska.gov/parks/boating/", importantNotes: "No mandatory boating education requirement. Voluntary courses are available and recommended.", fieldDayDetails: null },
    { slug: "arizona", description: "Arizona has no mandatory boating safety education requirement, though voluntary courses are available.", agencyName: "Arizona Game and Fish Department", agencyAbbreviation: "AZGFD", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.azgfd.com/boating/", importantNotes: "No mandatory boating education requirement. Voluntary courses are available.", fieldDayDetails: null },
    { slug: "arkansas", description: "Online boater education course approved by NASBLA. Arkansas requires boating safety education for anyone born on or after January 1, 1986.", agencyName: "Arkansas Game and Fish Commission", agencyAbbreviation: "AGFC", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.agfc.com/education/boater-education/", importantNotes: "Required for anyone born on or after January 1, 1986.", fieldDayDetails: null },
    { slug: "california", description: "Online boater education course approved by California Division of Boating and Waterways and NASBLA. Required for all motorized vessel operators.", agencyName: "California Division of Boating and Waterways", agencyAbbreviation: "DBW", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/california/", importantNotes: "Required for ALL motorized vessel operators as of January 1, 2025.", fieldDayDetails: null },
    { slug: "colorado", description: "Boater education course approved by Colorado Parks and Wildlife and NASBLA. Ages 14-15 require an in-person proctored exam.", agencyName: "Colorado Parks and Wildlife", agencyAbbreviation: "CPW", minimumAge: 14, fieldDayRequired: true, courseUrl: "https://recademics.com/boating/colorado/", importantNotes: "Required for ages 14-17 to operate motorboats. Under 14 cannot operate motorboats. Ages 14-15 require in-person proctored exam.", fieldDayDetails: "Ages 14-15 must complete an in-person classroom course with proctored exam. Ages 16+ may complete the course online." },
    { slug: "connecticut", description: "Connecticut requires an 8-hour in-person classroom boating safety course for all operators. Online-only courses do not satisfy Connecticut's requirement.", agencyName: "Connecticut Department of Energy and Environmental Protection", agencyAbbreviation: "DEEP", minimumAge: null, fieldDayRequired: true, courseUrl: "https://portal.ct.gov/DEEP/Boating/Education/Boating-Classes", importantNotes: "Required for all operators. Must complete an in-person 8-hour classroom course — online-only is not accepted.", fieldDayDetails: "An 8-hour in-person classroom course is required. Online-only courses do not meet Connecticut requirements." },
    { slug: "delaware", description: "Online boater education course approved by NASBLA. Delaware requires boating safety education for anyone born on or after January 1, 1978.", agencyName: "Delaware Department of Natural Resources and Environmental Control", agencyAbbreviation: "DNREC", minimumAge: null, fieldDayRequired: false, courseUrl: "https://dnrec.delaware.gov/fish-wildlife/boating/safety/", importantNotes: "Required for anyone born on or after January 1, 1978.", fieldDayDetails: null },
    { slug: "florida", description: "Online boater education course approved by Florida FWC and NASBLA. Required for boaters born on or after January 1, 1988.", agencyName: "Florida Fish and Wildlife Conservation Commission", agencyAbbreviation: "FWC", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/florida/", importantNotes: "Required for anyone born on or after January 1, 1988, operating vessels with 10+ hp.", fieldDayDetails: null },
    { slug: "georgia", description: "Online boater education course approved by Georgia DNR and NASBLA. Required for anyone born on or after January 1, 1998.", agencyName: "Georgia Department of Natural Resources - Wildlife Resources Division", agencyAbbreviation: "DNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://gadnrle.org/boating-education", importantNotes: "Required for anyone born on or after January 1, 1998.", fieldDayDetails: null },
    { slug: "hawaii", description: "Online boater education course approved by NASBLA. Hawaii requires education for operators of vessels with 10+ hp motors.", agencyName: "Hawaii Department of Land and Natural Resources - Division of Boating and Ocean Recreation", agencyAbbreviation: "DOBOR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/hawaii/", importantNotes: "Required for operators of vessels with 10+ hp motors.", fieldDayDetails: null },
    { slug: "idaho", description: "Idaho has no statewide mandatory boating education requirement, though voluntary courses are recommended.", agencyName: "Idaho Department of Parks and Recreation", agencyAbbreviation: "IDPR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/idaho/", importantNotes: "No statewide mandatory requirement. Voluntary courses available and recommended.", fieldDayDetails: null },
    { slug: "illinois", description: "Online boater education course approved by NASBLA. Illinois requires education for anyone born on or after January 1, 1998, operating 10+ hp.", agencyName: "Illinois Department of Natural Resources", agencyAbbreviation: "IDNR", minimumAge: 11, fieldDayRequired: false, courseUrl: "https://dnr.illinois.gov/safety/boatingsafety.html", importantNotes: "Required for anyone born on or after January 1, 1998, operating boats with 10+ hp. Minimum age 11 to take the exam.", fieldDayDetails: null },
    { slug: "indiana", description: "Online boater education course approved by NASBLA. Indiana requires education for operators age 15+ without a driver's license.", agencyName: "Indiana Department of Natural Resources - Law Enforcement Division", agencyAbbreviation: "DNR", minimumAge: 15, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/indiana/", importantNotes: "Required for operators age 15+ without a driver's license. No one under 15 may operate boats with 10+ hp.", fieldDayDetails: null },
    { slug: "iowa", description: "Online boater education course approved by Iowa DNR and NASBLA. Required for ages 12-17 operating boats with 10+ hp.", agencyName: "Iowa Department of Natural Resources", agencyAbbreviation: "DNR", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/iowa/", importantNotes: "Required for ages 12-17 operating boats with 10+ hp. No requirement for operators 18+.", fieldDayDetails: null },
    { slug: "kansas", description: "Online boater education course approved by NASBLA. Kansas requires education for anyone born on or after January 1, 1989.", agencyName: "Kansas Department of Wildlife and Parks", agencyAbbreviation: "KDWP", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/kansas/", importantNotes: "Required for anyone born on or after January 1, 1989.", fieldDayDetails: null },
    { slug: "kentucky", description: "Online boater education course approved by NASBLA. Kentucky requires education for operators ages 12-17.", agencyName: "Kentucky Department of Fish and Wildlife Resources", agencyAbbreviation: "KDFWR", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/kentucky/", importantNotes: "Required for operators ages 12-17. No requirement for operators 18+.", fieldDayDetails: null },
    { slug: "louisiana", description: "Online boater education course approved by NASBLA. Louisiana requires education for anyone born after January 1, 1984, operating 10+ hp boats.", agencyName: "Louisiana Department of Wildlife and Fisheries", agencyAbbreviation: "LDWF", minimumAge: 16, fieldDayRequired: false, courseUrl: "https://www.wlf.louisiana.gov/page/boater-education", importantNotes: "Required for anyone born after January 1, 1984, operating boats with 10+ hp or PWCs. Must be 16+ for PWC operation.", fieldDayDetails: null },
    { slug: "maine", description: "Online boater education course approved by NASBLA. Maine requires education for anyone born on or after January 1, 1999, operating 25+ hp boats.", agencyName: "Maine Department of Inland Fisheries and Wildlife", agencyAbbreviation: "DIFW", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://www.maine.gov/ifw/programs-resources/educational-programs/safety-courses/boating-safety.html", importantNotes: "Required for anyone born on or after January 1, 1999, operating boats with 25+ hp. PWC operators born after 1/1/1999 must be 16+.", fieldDayDetails: null },
    { slug: "maryland", description: "Online boater education course approved by Maryland DNR and NASBLA. Required for anyone born on or after July 1, 1972.", agencyName: "Maryland Department of Natural Resources", agencyAbbreviation: "DNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/maryland/", importantNotes: "Required for anyone born on or after July 1, 1972.", fieldDayDetails: null },
    { slug: "massachusetts", description: "Online boater education course approved by NASBLA. Massachusetts is phasing in a requirement for all boaters.", agencyName: "Massachusetts Environmental Police", agencyAbbreviation: "MEP", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.mass.gov/take-a-boating-safety-course", importantNotes: "Phased requirement: born after 1/1/1989 must complete by 4/1/2026; born before 1/1/1989 must complete by 4/1/2028.", fieldDayDetails: null },
    { slug: "michigan", description: "Online boater education course approved by NASBLA. Michigan requires education for anyone born on or after July 1, 1996.", agencyName: "Michigan Department of Natural Resources", agencyAbbreviation: "MDNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.michigan.gov/dnr/things-to-do/boating/safety-certificate", importantNotes: "Required for anyone born on or after July 1, 1996. PWC operators born after 12/31/1978 also require certification.", fieldDayDetails: null },
    { slug: "minnesota", description: "Online boater education course approved by NASBLA. Minnesota requires education for operators born on or after July 1, 2004.", agencyName: "Minnesota Department of Natural Resources", agencyAbbreviation: "DNR", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://www.dnr.state.mn.us/safety/boatwater/education.html", importantNotes: "Required for operators born on or after July 1, 2004. Phased rollout through 2028. Minimum age 12.", fieldDayDetails: null },
    { slug: "mississippi", description: "Online boater education course approved by NASBLA. Mississippi requires education for anyone born on or after June 30, 1980.", agencyName: "Mississippi Department of Wildlife, Fisheries and Parks", agencyAbbreviation: "MDWFP", minimumAge: 10, fieldDayRequired: false, courseUrl: "https://www.mdwfp.com/enforcement-education/boater-education", importantNotes: "Required for anyone born on or after June 30, 1980. Minimum age 10 to take the course.", fieldDayDetails: null },
    { slug: "missouri", description: "Online boater education course approved by NASBLA. Missouri requires education for anyone born after January 1, 1984.", agencyName: "Missouri State Highway Patrol - Water Patrol", agencyAbbreviation: "MSHP", minimumAge: 14, fieldDayRequired: false, courseUrl: "https://www.mshp.dps.missouri.gov/MSHPWeb/WaterPatrol/BoatingLaws_Education/boaterEduLawFAQ.html", importantNotes: "Required for anyone born after January 1, 1984. Must be age 14+ to operate.", fieldDayDetails: null },
    { slug: "montana", description: "Online boater education course approved by NASBLA. Montana requires education for operators ages 13-14 on boats with 10+ hp.", agencyName: "Montana Fish, Wildlife and Parks", agencyAbbreviation: "FWP", minimumAge: 13, fieldDayRequired: false, courseUrl: "https://fwp.mt.gov/activities/boating/education", importantNotes: "Required for operators ages 13-14 on boats with 10+ hp motors. No requirement for age 15+.", fieldDayDetails: null },
    { slug: "nebraska", description: "Online boater education course approved by NASBLA. Nebraska requires education for anyone born after December 31, 1985.", agencyName: "Nebraska Game and Parks Commission", agencyAbbreviation: "NGPC", minimumAge: 14, fieldDayRequired: false, courseUrl: "https://outdoornebraska.gov/parks/go-boating/boater-education/", importantNotes: "Required for anyone born after December 31, 1985. Must be age 14+ to operate.", fieldDayDetails: null },
    { slug: "nevada", description: "Online boater education course approved by NASBLA. Nevada requires education for anyone born on or after January 1, 1983, operating 15+ hp.", agencyName: "Nevada Department of Wildlife", agencyAbbreviation: "NDOW", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/nevada/", importantNotes: "Required for anyone born on or after January 1, 1983, operating boats with 15+ hp.", fieldDayDetails: null },
    { slug: "new-hampshire", description: "New Hampshire requires an 8-hour in-person proctored classroom course for boating safety. Online-only courses do not satisfy the requirement.", agencyName: "New Hampshire State Police - Marine Patrol", agencyAbbreviation: "NHSP", minimumAge: 16, fieldDayRequired: true, courseUrl: "https://www.nhsp.dos.nh.gov/our-services/field-operations-bureau/marine-patrol/boating-education", importantNotes: "Required for age 16+ operating motorboats with 25+ hp or ski craft. Must complete 8-hour in-person classroom course.", fieldDayDetails: "An 8-hour in-person proctored classroom course is required. Online-only courses do not meet NH requirements." },
    { slug: "new-jersey", description: "Boater education course approved by NASBLA. New Jersey requires an in-person proctored exam after completing the online portion.", agencyName: "New Jersey State Police - Marine Services Bureau", agencyAbbreviation: "NJSP", minimumAge: 16, fieldDayRequired: true, courseUrl: "https://recademics.com/boating/new-jersey/", importantNotes: "Required for age 16+ for all motorboats and PWCs. Must complete in-person proctored exam after online course.", fieldDayDetails: "An in-person proctored exam is required after completing the online course portion." },
    { slug: "new-mexico", description: "Online boater education course approved by NASBLA. New Mexico requires education for anyone born on or after January 1, 1989.", agencyName: "New Mexico State Parks Division", agencyAbbreviation: "EMNRD", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.emnrd.nm.gov/spd/activities/boating-2/boating-education/", importantNotes: "Required for anyone born on or after January 1, 1989.", fieldDayDetails: null },
    { slug: "new-york", description: "Online boater education course approved by New York State Parks and NASBLA. Required for ALL motorized vessel operators.", agencyName: "New York State Parks, Recreation and Historic Preservation", agencyAbbreviation: "NYSPARKS", minimumAge: 10, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/new-york/", importantNotes: "Required for ALL motorized vessel operators as of January 1, 2025. Minimum age 10 to take the course.", fieldDayDetails: null },
    { slug: "north-carolina", description: "Online boater education course approved by NC Wildlife Resources Commission and NASBLA. Required for anyone born on or after January 1, 1988.", agencyName: "North Carolina Wildlife Resources Commission", agencyAbbreviation: "NCWRC", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/north-carolina/", importantNotes: "Required for anyone born on or after January 1, 1988.", fieldDayDetails: null },
    { slug: "north-dakota", description: "Online boater education course approved by NASBLA. North Dakota requires education for operators ages 12-15 on boats with 10+ hp.", agencyName: "North Dakota Game and Fish Department", agencyAbbreviation: "NDGF", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://gf.nd.gov/education/boating", importantNotes: "Required for operators ages 12-15 on boats with 10+ hp. No requirement for operators 16+.", fieldDayDetails: null },
    { slug: "ohio", description: "Online boater education course approved by Ohio ODNR and NASBLA. Required for anyone born on or after January 1, 1982, operating 10+ hp.", agencyName: "Ohio Department of Natural Resources", agencyAbbreviation: "ODNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/ohio/", importantNotes: "Required for anyone born on or after January 1, 1982, operating boats with 10+ hp.", fieldDayDetails: null },
    { slug: "oklahoma", description: "Online boater education course approved by NASBLA. Oklahoma requires education for operators ages 12-15 on boats with 10+ hp.", agencyName: "Oklahoma Department of Wildlife Conservation", agencyAbbreviation: "ODWC", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://oklahoma.gov/dps/programs-services/boated.html", importantNotes: "Required for operators ages 12-15 on boats with 10+ hp, sailboats 16+ ft, or PWCs.", fieldDayDetails: null },
    { slug: "oregon", description: "Online boater education course approved by Oregon State Marine Board and NASBLA. Required for age 16+ operating boats with 10+ hp.", agencyName: "Oregon State Marine Board", agencyAbbreviation: "OSMB", minimumAge: 16, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/oregon/", importantNotes: "Required for age 16+ operating boats with 10+ hp. Online and classroom options available.", fieldDayDetails: null },
    { slug: "pennsylvania", description: "Online boater education course approved by PA Fish and Boat Commission and NASBLA. Required for operators born on or after January 1, 1982.", agencyName: "Pennsylvania Fish and Boat Commission", agencyAbbreviation: "PFBC", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.pa.gov/services/fishandboat/apply-for-bsec-and-safety-courses", importantNotes: "Required for anyone born on or after January 1, 1982, operating boats with 25+ hp. ALL PWC operators require certification regardless of age.", fieldDayDetails: null },
    { slug: "rhode-island", description: "Rhode Island requires an 8-hour course with a proctored written exam under certified instructor supervision for boating safety certification.", agencyName: "Rhode Island Department of Environmental Management", agencyAbbreviation: "RIDEM", minimumAge: null, fieldDayRequired: true, courseUrl: "https://dem.ri.gov/natural-resources-bureau/law-enforcement/boating-safety-certification", importantNotes: "Required for anyone born on or after January 1, 1986, operating boats with 10+ hp. Must complete 8-hour in-person course with proctored exam.", fieldDayDetails: "An 8-hour course with a proctored written exam under certified instructor supervision is required." },
    { slug: "south-carolina", description: "Online boater education course approved by NASBLA. South Carolina requires education for anyone born after July 1, 2007.", agencyName: "South Carolina Department of Natural Resources", agencyAbbreviation: "SCDNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://www.dnr.sc.gov/education/boated.html", importantNotes: "Required for anyone born after July 1, 2007.", fieldDayDetails: null },
    { slug: "south-dakota", description: "South Dakota has no mandatory boating safety education requirement, though voluntary courses are available.", agencyName: "South Dakota Game, Fish and Parks", agencyAbbreviation: "SDGFP", minimumAge: null, fieldDayRequired: false, courseUrl: "https://gfp.sd.gov/", importantNotes: "No mandatory boating education requirement. Voluntary courses are available.", fieldDayDetails: null },
    { slug: "tennessee", description: "Online boater education course approved by TWRA and NASBLA. Tennessee requires education for anyone born after January 1, 1989.", agencyName: "Tennessee Wildlife Resources Agency", agencyAbbreviation: "TWRA", minimumAge: null, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/tennessee/", importantNotes: "Required for anyone born after January 1, 1989.", fieldDayDetails: null },
    { slug: "texas", description: "Online boater education course approved by Texas Parks and Wildlife and NASBLA. Required for anyone born on or after September 1, 1993.", agencyName: "Texas Parks and Wildlife Department", agencyAbbreviation: "TPWD", minimumAge: 13, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/texas/", importantNotes: "Required for anyone born on or after September 1, 1993. Minimum age 13.", fieldDayDetails: null },
    { slug: "utah", description: "Online boater education course approved by NASBLA. Utah requires education for PWC operators ages 12-17.", agencyName: "Utah Division of Outdoor Recreation", agencyAbbreviation: "DOR", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://recreation.utah.gov/boating/boating-education/", importantNotes: "Required for PWC operators ages 12-17. No requirement for adult motorboat operators.", fieldDayDetails: null },
    { slug: "vermont", description: "Online boater education course approved by NASBLA. Vermont requires education for anyone born on or after January 1, 1974, operating motorized vessels.", agencyName: "Vermont Fish and Wildlife Department", agencyAbbreviation: "VFWD", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://www.vtfishandwildlife.com/fish/boating-in-vermont", importantNotes: "Required for anyone born on or after January 1, 1974, operating motorized vessels.", fieldDayDetails: null },
    { slug: "virginia", description: "Online boater education course approved by Virginia DWR and NASBLA. Required for PWC operators age 14+ and all motorboat operators with 10+ hp.", agencyName: "Virginia Department of Wildlife Resources", agencyAbbreviation: "DWR", minimumAge: 14, fieldDayRequired: false, courseUrl: "https://recademics.com/boating/virginia/", importantNotes: "Required for PWC operators age 14+ and all motorboat operators with 10+ hp.", fieldDayDetails: null },
    { slug: "washington", description: "Online boater education course approved by NASBLA. Washington requires education for operators of motorboats with 15+ hp.", agencyName: "Washington State Parks and Recreation Commission", agencyAbbreviation: "WSPRC", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://parks.wa.gov/about/rules-and-safety/boater-education-safety/boater-education-card", importantNotes: "Required for operators of motorboats with 15+ hp, unless born before January 1, 1955.", fieldDayDetails: null },
    { slug: "west-virginia", description: "Online boater education course approved by NASBLA. West Virginia requires education for anyone born after December 31, 1986.", agencyName: "West Virginia Division of Natural Resources", agencyAbbreviation: "WVDNR", minimumAge: null, fieldDayRequired: false, courseUrl: "https://wvdnr.gov/boater-education/", importantNotes: "Required for anyone born after December 31, 1986.", fieldDayDetails: null },
    { slug: "wisconsin", description: "Online boater education course approved by NASBLA. Wisconsin requires education for operators age 12+ born on or after January 1, 1989.", agencyName: "Wisconsin Department of Natural Resources", agencyAbbreviation: "WDNR", minimumAge: 12, fieldDayRequired: false, courseUrl: "https://dnr.wisconsin.gov/Education/OutdoorSkills/safetyEducation", importantNotes: "Required for operators age 12+ born on or after January 1, 1989.", fieldDayDetails: null },
    { slug: "wyoming", description: "Wyoming has no mandatory boating safety education requirement, though voluntary courses are available.", agencyName: "Wyoming Game and Fish Department", agencyAbbreviation: "WGFD", minimumAge: null, fieldDayRequired: false, courseUrl: "https://wgfd.wyo.gov/fishing-boating/boating-watercraft", importantNotes: "No mandatory boating education requirement. Voluntary courses are available.", fieldDayDetails: null },
  ];

  for (const state of stateUpdates) {
    await db.execute(sql`
      UPDATE states SET
        description = ${state.description},
        agency_name = ${state.agencyName},
        agency_abbreviation = ${state.agencyAbbreviation},
        minimum_age = ${state.minimumAge},
        field_day_required = ${state.fieldDayRequired},
        course_url = ${state.courseUrl},
        important_notes = ${state.importantNotes},
        field_day_details = ${state.fieldDayDetails}
      WHERE slug = ${state.slug}
    `);
  }

  console.log("State data accuracy updates complete.");

  console.log("Database migrations complete.");
}
