import { db } from "./db";
import { states, articles } from "@shared/schema";
import { eq } from "drizzle-orm";

export async function seedDatabase() {
  const existingStates = await db.select().from(states).limit(1);
  if (existingStates.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding boater education database...");

  const stateData = [
    {
      name: "Alabama",
      abbreviation: "AL",
      slug: "alabama",
      description: "Online boater education course approved by NASBLA. Alabama requires boater education for operators age 12+ on motorboats with 15+ hp.",
      agencyName: "Alabama Law Enforcement Agency - Marine Patrol Division",
      agencyAbbreviation: "ALEA",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://www.alea.gov/dps/marine-patrol/boating-education-and-operator-certificationlicense",
      importantNotes: "Required for operators age 12+ on motorboats with 15+ hp. Operators ages 12-13 must have adult supervision.",
      isActive: true,
    },
    {
      name: "Alaska",
      abbreviation: "AK",
      slug: "alaska",
      description: "Alaska has no mandatory boating safety education requirement, though courses are recommended for all boaters.",
      agencyName: "Alaska Department of Natural Resources - Office of Boating Safety",
      agencyAbbreviation: "DNR",
      fieldDayRequired: false,
      courseUrl: "https://dnr.alaska.gov/parks/boating/",
      importantNotes: "No mandatory boating education requirement. Voluntary courses are available and recommended.",
      isActive: true,
    },
    {
      name: "Arizona",
      abbreviation: "AZ",
      slug: "arizona",
      description: "Arizona has no mandatory boating safety education requirement, though voluntary courses are available.",
      agencyName: "Arizona Game and Fish Department",
      agencyAbbreviation: "AZGFD",
      fieldDayRequired: false,
      courseUrl: "https://www.azgfd.com/boating/",
      importantNotes: "No mandatory boating education requirement. Voluntary courses are available.",
      isActive: true,
    },
    {
      name: "Arkansas",
      abbreviation: "AR",
      slug: "arkansas",
      description: "Online boater education course approved by NASBLA. Arkansas requires boating safety education for anyone born on or after January 1, 1986.",
      agencyName: "Arkansas Game and Fish Commission",
      agencyAbbreviation: "AGFC",
      fieldDayRequired: false,
      courseUrl: "https://www.agfc.com/education/boater-education/",
      importantNotes: "Required for anyone born on or after January 1, 1986.",
      isActive: true,
    },
    {
      name: "California",
      abbreviation: "CA",
      slug: "california",
      description: "Online boater education course approved by California Division of Boating and Waterways and NASBLA. Required for all motorized vessel operators.",
      agencyName: "California Division of Boating and Waterways",
      agencyAbbreviation: "DBW",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/california/",
      importantNotes: "Required for ALL motorized vessel operators as of January 1, 2025.",
      isActive: true,
    },
    {
      name: "Colorado",
      abbreviation: "CO",
      slug: "colorado",
      description: "Boater education course approved by Colorado Parks and Wildlife and NASBLA. Ages 14-15 require an in-person proctored exam.",
      agencyName: "Colorado Parks and Wildlife",
      agencyAbbreviation: "CPW",
      minimumAge: 14,
      fieldDayRequired: true,
      courseUrl: "https://recademics.com/boating/colorado/",
      fieldDayDetails: "Ages 14-15 must complete an in-person classroom course with proctored exam. Ages 16+ may complete the course online.",
      importantNotes: "Required for ages 14-17 to operate motorboats. Under 14 cannot operate motorboats. Ages 14-15 require in-person proctored exam.",
      isActive: true,
    },
    {
      name: "Connecticut",
      abbreviation: "CT",
      slug: "connecticut",
      description: "Connecticut requires an 8-hour in-person classroom boating safety course for all operators. Online-only courses do not satisfy Connecticut's requirement.",
      agencyName: "Connecticut Department of Energy and Environmental Protection",
      agencyAbbreviation: "DEEP",
      fieldDayRequired: true,
      courseUrl: "https://portal.ct.gov/DEEP/Boating/Education/Boating-Classes",
      fieldDayDetails: "An 8-hour in-person classroom course is required. Online-only courses do not meet Connecticut requirements.",
      importantNotes: "Required for all operators. Must complete an in-person 8-hour classroom course — online-only is not accepted.",
      isActive: true,
    },
    {
      name: "Delaware",
      abbreviation: "DE",
      slug: "delaware",
      description: "Online boater education course approved by NASBLA. Delaware requires boating safety education for anyone born on or after January 1, 1978.",
      agencyName: "Delaware Department of Natural Resources and Environmental Control",
      agencyAbbreviation: "DNREC",
      fieldDayRequired: false,
      courseUrl: "https://dnrec.delaware.gov/fish-wildlife/boating/safety/",
      importantNotes: "Required for anyone born on or after January 1, 1978.",
      isActive: true,
    },
    {
      name: "Florida",
      abbreviation: "FL",
      slug: "florida",
      description: "Online boater education course approved by Florida FWC and NASBLA. Required for boaters born on or after January 1, 1988.",
      agencyName: "Florida Fish and Wildlife Conservation Commission",
      agencyAbbreviation: "FWC",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/florida/",
      importantNotes: "Required for anyone born on or after January 1, 1988, operating vessels with 10+ hp.",
      isActive: true,
    },
    {
      name: "Georgia",
      abbreviation: "GA",
      slug: "georgia",
      description: "Online boater education course approved by Georgia DNR and NASBLA. Required for anyone born on or after January 1, 1998.",
      agencyName: "Georgia Department of Natural Resources - Wildlife Resources Division",
      agencyAbbreviation: "DNR",
      fieldDayRequired: false,
      courseUrl: "https://gadnrle.org/boating-education",
      importantNotes: "Required for anyone born on or after January 1, 1998.",
      isActive: true,
    },
    {
      name: "Hawaii",
      abbreviation: "HI",
      slug: "hawaii",
      description: "Online boater education course approved by NASBLA. Hawaii requires education for operators of vessels with 10+ hp motors.",
      agencyName: "Hawaii Department of Land and Natural Resources - Division of Boating and Ocean Recreation",
      agencyAbbreviation: "DOBOR",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/hawaii/",
      importantNotes: "Required for operators of vessels with 10+ hp motors.",
      isActive: true,
    },
    {
      name: "Idaho",
      abbreviation: "ID",
      slug: "idaho",
      description: "Idaho has no statewide mandatory boating education requirement, though voluntary courses are recommended.",
      agencyName: "Idaho Department of Parks and Recreation",
      agencyAbbreviation: "IDPR",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/idaho/",
      importantNotes: "No statewide mandatory requirement. Voluntary courses available and recommended.",
      isActive: true,
    },
    {
      name: "Illinois",
      abbreviation: "IL",
      slug: "illinois",
      description: "Online boater education course approved by NASBLA. Illinois requires education for anyone born on or after January 1, 1998, operating 10+ hp.",
      agencyName: "Illinois Department of Natural Resources",
      agencyAbbreviation: "IDNR",
      minimumAge: 11,
      fieldDayRequired: false,
      courseUrl: "https://dnr.illinois.gov/safety/boatingsafety.html",
      importantNotes: "Required for anyone born on or after January 1, 1998, operating boats with 10+ hp. Minimum age 11 to take the exam.",
      isActive: true,
    },
    {
      name: "Indiana",
      abbreviation: "IN",
      slug: "indiana",
      description: "Online boater education course approved by NASBLA. Indiana requires education for operators age 15+ without a driver's license.",
      agencyName: "Indiana Department of Natural Resources - Law Enforcement Division",
      agencyAbbreviation: "DNR",
      minimumAge: 15,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/indiana/",
      importantNotes: "Required for operators age 15+ without a driver's license. No one under 15 may operate boats with 10+ hp.",
      isActive: true,
    },
    {
      name: "Iowa",
      abbreviation: "IA",
      slug: "iowa",
      description: "Online boater education course approved by Iowa DNR and NASBLA. Required for ages 12-17 operating boats with 10+ hp.",
      agencyName: "Iowa Department of Natural Resources",
      agencyAbbreviation: "DNR",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/iowa/",
      importantNotes: "Required for ages 12-17 operating boats with 10+ hp. No requirement for operators 18+.",
      isActive: true,
    },
    {
      name: "Kansas",
      abbreviation: "KS",
      slug: "kansas",
      description: "Online boater education course approved by NASBLA. Kansas requires education for anyone born on or after January 1, 1989.",
      agencyName: "Kansas Department of Wildlife and Parks",
      agencyAbbreviation: "KDWP",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/kansas/",
      importantNotes: "Required for anyone born on or after January 1, 1989.",
      isActive: true,
    },
    {
      name: "Kentucky",
      abbreviation: "KY",
      slug: "kentucky",
      description: "Online boater education course approved by NASBLA. Kentucky requires education for operators ages 12-17.",
      agencyName: "Kentucky Department of Fish and Wildlife Resources",
      agencyAbbreviation: "KDFWR",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/kentucky/",
      importantNotes: "Required for operators ages 12-17. No requirement for operators 18+.",
      isActive: true,
    },
    {
      name: "Louisiana",
      abbreviation: "LA",
      slug: "louisiana",
      description: "Online boater education course approved by NASBLA. Louisiana requires education for anyone born after January 1, 1984, operating 10+ hp boats.",
      agencyName: "Louisiana Department of Wildlife and Fisheries",
      agencyAbbreviation: "LDWF",
      minimumAge: 16,
      fieldDayRequired: false,
      courseUrl: "https://www.wlf.louisiana.gov/page/boater-education",
      importantNotes: "Required for anyone born after January 1, 1984, operating boats with 10+ hp or PWCs. Must be 16+ for PWC operation.",
      isActive: true,
    },
    {
      name: "Maine",
      abbreviation: "ME",
      slug: "maine",
      description: "Online boater education course approved by NASBLA. Maine requires education for anyone born on or after January 1, 1999, operating 25+ hp boats.",
      agencyName: "Maine Department of Inland Fisheries and Wildlife",
      agencyAbbreviation: "DIFW",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://www.maine.gov/ifw/programs-resources/educational-programs/safety-courses/boating-safety.html",
      importantNotes: "Required for anyone born on or after January 1, 1999, operating boats with 25+ hp. PWC operators born after 1/1/1999 must be 16+.",
      isActive: true,
    },
    {
      name: "Maryland",
      abbreviation: "MD",
      slug: "maryland",
      description: "Online boater education course approved by Maryland DNR and NASBLA. Required for anyone born on or after July 1, 1972.",
      agencyName: "Maryland Department of Natural Resources",
      agencyAbbreviation: "DNR",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/maryland/",
      importantNotes: "Required for anyone born on or after July 1, 1972.",
      isActive: true,
    },
    {
      name: "Massachusetts",
      abbreviation: "MA",
      slug: "massachusetts",
      description: "Online boater education course approved by NASBLA. Massachusetts is phasing in a requirement for all boaters.",
      agencyName: "Massachusetts Environmental Police",
      agencyAbbreviation: "MEP",
      fieldDayRequired: false,
      courseUrl: "https://www.mass.gov/take-a-boating-safety-course",
      importantNotes: "Phased requirement: born after 1/1/1989 must complete by 4/1/2026; born before 1/1/1989 must complete by 4/1/2028.",
      isActive: true,
    },
    {
      name: "Michigan",
      abbreviation: "MI",
      slug: "michigan",
      description: "Online boater education course approved by NASBLA. Michigan requires education for anyone born on or after July 1, 1996.",
      agencyName: "Michigan Department of Natural Resources",
      agencyAbbreviation: "MDNR",
      fieldDayRequired: false,
      courseUrl: "https://www.michigan.gov/dnr/things-to-do/boating/safety-certificate",
      importantNotes: "Required for anyone born on or after July 1, 1996. PWC operators born after 12/31/1978 also require certification.",
      isActive: true,
    },
    {
      name: "Minnesota",
      abbreviation: "MN",
      slug: "minnesota",
      description: "Online boater education course approved by NASBLA. Minnesota requires education for operators born on or after July 1, 2004.",
      agencyName: "Minnesota Department of Natural Resources",
      agencyAbbreviation: "DNR",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://www.dnr.state.mn.us/safety/boatwater/education.html",
      importantNotes: "Required for operators born on or after July 1, 2004. Phased rollout through 2028. Minimum age 12.",
      isActive: true,
    },
    {
      name: "Mississippi",
      abbreviation: "MS",
      slug: "mississippi",
      description: "Online boater education course approved by NASBLA. Mississippi requires education for anyone born on or after June 30, 1980.",
      agencyName: "Mississippi Department of Wildlife, Fisheries and Parks",
      agencyAbbreviation: "MDWFP",
      minimumAge: 10,
      fieldDayRequired: false,
      courseUrl: "https://www.mdwfp.com/enforcement-education/boater-education",
      importantNotes: "Required for anyone born on or after June 30, 1980. Minimum age 10 to take the course.",
      isActive: true,
    },
    {
      name: "Missouri",
      abbreviation: "MO",
      slug: "missouri",
      description: "Online boater education course approved by NASBLA. Missouri requires education for anyone born after January 1, 1984.",
      agencyName: "Missouri State Highway Patrol - Water Patrol",
      agencyAbbreviation: "MSHP",
      minimumAge: 14,
      fieldDayRequired: false,
      courseUrl: "https://www.mshp.dps.missouri.gov/MSHPWeb/WaterPatrol/BoatingLaws_Education/boaterEduLawFAQ.html",
      importantNotes: "Required for anyone born after January 1, 1984. Must be age 14+ to operate.",
      isActive: true,
    },
    {
      name: "Montana",
      abbreviation: "MT",
      slug: "montana",
      description: "Online boater education course approved by NASBLA. Montana requires education for operators ages 13-14 on boats with 10+ hp.",
      agencyName: "Montana Fish, Wildlife and Parks",
      agencyAbbreviation: "FWP",
      minimumAge: 13,
      fieldDayRequired: false,
      courseUrl: "https://fwp.mt.gov/activities/boating/education",
      importantNotes: "Required for operators ages 13-14 on boats with 10+ hp motors. No requirement for age 15+.",
      isActive: true,
    },
    {
      name: "Nebraska",
      abbreviation: "NE",
      slug: "nebraska",
      description: "Online boater education course approved by NASBLA. Nebraska requires education for anyone born after December 31, 1985.",
      agencyName: "Nebraska Game and Parks Commission",
      agencyAbbreviation: "NGPC",
      minimumAge: 14,
      fieldDayRequired: false,
      courseUrl: "https://outdoornebraska.gov/parks/go-boating/boater-education/",
      importantNotes: "Required for anyone born after December 31, 1985. Must be age 14+ to operate.",
      isActive: true,
    },
    {
      name: "Nevada",
      abbreviation: "NV",
      slug: "nevada",
      description: "Online boater education course approved by NASBLA. Nevada requires education for anyone born on or after January 1, 1983, operating 15+ hp.",
      agencyName: "Nevada Department of Wildlife",
      agencyAbbreviation: "NDOW",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/nevada/",
      importantNotes: "Required for anyone born on or after January 1, 1983, operating boats with 15+ hp.",
      isActive: true,
    },
    {
      name: "New Hampshire",
      abbreviation: "NH",
      slug: "new-hampshire",
      description: "New Hampshire requires an 8-hour in-person proctored classroom course for boating safety. Online-only courses do not satisfy the requirement.",
      agencyName: "New Hampshire State Police - Marine Patrol",
      agencyAbbreviation: "NHSP",
      minimumAge: 16,
      fieldDayRequired: true,
      courseUrl: "https://www.nhsp.dos.nh.gov/our-services/field-operations-bureau/marine-patrol/boating-education",
      fieldDayDetails: "An 8-hour in-person proctored classroom course is required. Online-only courses do not meet NH requirements.",
      importantNotes: "Required for age 16+ operating motorboats with 25+ hp or ski craft. Must complete 8-hour in-person classroom course.",
      isActive: true,
    },
    {
      name: "New Jersey",
      abbreviation: "NJ",
      slug: "new-jersey",
      description: "Boater education course approved by NASBLA. New Jersey requires an in-person proctored exam after completing the online portion.",
      agencyName: "New Jersey State Police - Marine Services Bureau",
      agencyAbbreviation: "NJSP",
      minimumAge: 16,
      fieldDayRequired: true,
      courseUrl: "https://recademics.com/boating/new-jersey/",
      fieldDayDetails: "An in-person proctored exam is required after completing the online course portion.",
      importantNotes: "Required for age 16+ for all motorboats and PWCs. Must complete in-person proctored exam after online course.",
      isActive: true,
    },
    {
      name: "New Mexico",
      abbreviation: "NM",
      slug: "new-mexico",
      description: "Online boater education course approved by NASBLA. New Mexico requires education for anyone born on or after January 1, 1989.",
      agencyName: "New Mexico State Parks Division",
      agencyAbbreviation: "EMNRD",
      fieldDayRequired: false,
      courseUrl: "https://www.emnrd.nm.gov/spd/activities/boating-2/boating-education/",
      importantNotes: "Required for anyone born on or after January 1, 1989.",
      isActive: true,
    },
    {
      name: "New York",
      abbreviation: "NY",
      slug: "new-york",
      description: "Online boater education course approved by New York State Parks and NASBLA. Required for ALL motorized vessel operators.",
      agencyName: "New York State Parks, Recreation and Historic Preservation",
      agencyAbbreviation: "NYSPARKS",
      minimumAge: 10,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/new-york/",
      importantNotes: "Required for ALL motorized vessel operators as of January 1, 2025. Minimum age 10 to take the course.",
      isActive: true,
    },
    {
      name: "North Carolina",
      abbreviation: "NC",
      slug: "north-carolina",
      description: "Online boater education course approved by NC Wildlife Resources Commission and NASBLA. Required for anyone born on or after January 1, 1988.",
      agencyName: "North Carolina Wildlife Resources Commission",
      agencyAbbreviation: "NCWRC",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/north-carolina/",
      importantNotes: "Required for anyone born on or after January 1, 1988.",
      isActive: true,
    },
    {
      name: "North Dakota",
      abbreviation: "ND",
      slug: "north-dakota",
      description: "Online boater education course approved by NASBLA. North Dakota requires education for operators ages 12-15 on boats with 10+ hp.",
      agencyName: "North Dakota Game and Fish Department",
      agencyAbbreviation: "NDGF",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://gf.nd.gov/education/boating",
      importantNotes: "Required for operators ages 12-15 on boats with 10+ hp. No requirement for operators 16+.",
      isActive: true,
    },
    {
      name: "Ohio",
      abbreviation: "OH",
      slug: "ohio",
      description: "Online boater education course approved by Ohio ODNR and NASBLA. Required for anyone born on or after January 1, 1982, operating 10+ hp.",
      agencyName: "Ohio Department of Natural Resources",
      agencyAbbreviation: "ODNR",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/ohio/",
      importantNotes: "Required for anyone born on or after January 1, 1982, operating boats with 10+ hp.",
      isActive: true,
    },
    {
      name: "Oklahoma",
      abbreviation: "OK",
      slug: "oklahoma",
      description: "Online boater education course approved by NASBLA. Oklahoma requires education for operators ages 12-15 on boats with 10+ hp.",
      agencyName: "Oklahoma Department of Wildlife Conservation",
      agencyAbbreviation: "ODWC",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://oklahoma.gov/dps/programs-services/boated.html",
      importantNotes: "Required for operators ages 12-15 on boats with 10+ hp, sailboats 16+ ft, or PWCs.",
      isActive: true,
    },
    {
      name: "Oregon",
      abbreviation: "OR",
      slug: "oregon",
      description: "Online boater education course approved by Oregon State Marine Board and NASBLA. Required for age 16+ operating boats with 10+ hp.",
      agencyName: "Oregon State Marine Board",
      agencyAbbreviation: "OSMB",
      minimumAge: 16,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/oregon/",
      importantNotes: "Required for age 16+ operating boats with 10+ hp. Online and classroom options available.",
      isActive: true,
    },
    {
      name: "Pennsylvania",
      abbreviation: "PA",
      slug: "pennsylvania",
      description: "Online boater education course approved by PA Fish and Boat Commission and NASBLA. Required for operators born on or after January 1, 1982.",
      agencyName: "Pennsylvania Fish and Boat Commission",
      agencyAbbreviation: "PFBC",
      fieldDayRequired: false,
      courseUrl: "https://www.pa.gov/services/fishandboat/apply-for-bsec-and-safety-courses",
      importantNotes: "Required for anyone born on or after January 1, 1982, operating boats with 25+ hp. ALL PWC operators require certification regardless of age.",
      isActive: true,
    },
    {
      name: "Rhode Island",
      abbreviation: "RI",
      slug: "rhode-island",
      description: "Rhode Island requires an 8-hour course with a proctored written exam under certified instructor supervision for boating safety certification.",
      agencyName: "Rhode Island Department of Environmental Management",
      agencyAbbreviation: "RIDEM",
      fieldDayRequired: true,
      courseUrl: "https://dem.ri.gov/natural-resources-bureau/law-enforcement/boating-safety-certification",
      fieldDayDetails: "An 8-hour course with a proctored written exam under certified instructor supervision is required.",
      importantNotes: "Required for anyone born on or after January 1, 1986, operating boats with 10+ hp. Must complete 8-hour in-person course with proctored exam.",
      isActive: true,
    },
    {
      name: "South Carolina",
      abbreviation: "SC",
      slug: "south-carolina",
      description: "Online boater education course approved by NASBLA. South Carolina requires education for anyone born after July 1, 2007.",
      agencyName: "South Carolina Department of Natural Resources",
      agencyAbbreviation: "SCDNR",
      fieldDayRequired: false,
      courseUrl: "https://www.dnr.sc.gov/education/boated.html",
      importantNotes: "Required for anyone born after July 1, 2007.",
      isActive: true,
    },
    {
      name: "South Dakota",
      abbreviation: "SD",
      slug: "south-dakota",
      description: "South Dakota has no mandatory boating safety education requirement, though voluntary courses are available.",
      agencyName: "South Dakota Game, Fish and Parks",
      agencyAbbreviation: "SDGFP",
      fieldDayRequired: false,
      courseUrl: "https://gfp.sd.gov/",
      importantNotes: "No mandatory boating education requirement. Voluntary courses are available.",
      isActive: true,
    },
    {
      name: "Tennessee",
      abbreviation: "TN",
      slug: "tennessee",
      description: "Online boater education course approved by TWRA and NASBLA. Tennessee requires education for anyone born after January 1, 1989.",
      agencyName: "Tennessee Wildlife Resources Agency",
      agencyAbbreviation: "TWRA",
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/tennessee/",
      importantNotes: "Required for anyone born after January 1, 1989.",
      isActive: true,
    },
    {
      name: "Texas",
      abbreviation: "TX",
      slug: "texas",
      description: "Online boater education course approved by Texas Parks and Wildlife and NASBLA. Required for anyone born on or after September 1, 1993.",
      agencyName: "Texas Parks and Wildlife Department",
      agencyAbbreviation: "TPWD",
      minimumAge: 13,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/texas/",
      importantNotes: "Required for anyone born on or after September 1, 1993. Minimum age 13.",
      isActive: true,
    },
    {
      name: "Utah",
      abbreviation: "UT",
      slug: "utah",
      description: "Online boater education course approved by NASBLA. Utah requires education for PWC operators ages 12-17.",
      agencyName: "Utah Division of Outdoor Recreation",
      agencyAbbreviation: "DOR",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://recreation.utah.gov/boating/boating-education/",
      importantNotes: "Required for PWC operators ages 12-17. No requirement for adult motorboat operators.",
      isActive: true,
    },
    {
      name: "Vermont",
      abbreviation: "VT",
      slug: "vermont",
      description: "Online boater education course approved by NASBLA. Vermont requires education for anyone born on or after January 1, 1974, operating motorized vessels.",
      agencyName: "Vermont Fish and Wildlife Department",
      agencyAbbreviation: "VFWD",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://www.vtfishandwildlife.com/fish/boating-in-vermont",
      importantNotes: "Required for anyone born on or after January 1, 1974, operating motorized vessels.",
      isActive: true,
    },
    {
      name: "Virginia",
      abbreviation: "VA",
      slug: "virginia",
      description: "Online boater education course approved by Virginia DWR and NASBLA. Required for PWC operators age 14+ and all motorboat operators with 10+ hp.",
      agencyName: "Virginia Department of Wildlife Resources",
      agencyAbbreviation: "DWR",
      minimumAge: 14,
      fieldDayRequired: false,
      courseUrl: "https://recademics.com/boating/virginia/",
      importantNotes: "Required for PWC operators age 14+ and all motorboat operators with 10+ hp.",
      isActive: true,
    },
    {
      name: "Washington",
      abbreviation: "WA",
      slug: "washington",
      description: "Online boater education course approved by NASBLA. Washington requires education for operators of motorboats with 15+ hp.",
      agencyName: "Washington State Parks and Recreation Commission",
      agencyAbbreviation: "WSPRC",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://parks.wa.gov/about/rules-and-safety/boater-education-safety/boater-education-card",
      importantNotes: "Required for operators of motorboats with 15+ hp, unless born before January 1, 1955.",
      isActive: true,
    },
    {
      name: "West Virginia",
      abbreviation: "WV",
      slug: "west-virginia",
      description: "Online boater education course approved by NASBLA. West Virginia requires education for anyone born after December 31, 1986.",
      agencyName: "West Virginia Division of Natural Resources",
      agencyAbbreviation: "WVDNR",
      fieldDayRequired: false,
      courseUrl: "https://wvdnr.gov/boater-education/",
      importantNotes: "Required for anyone born after December 31, 1986.",
      isActive: true,
    },
    {
      name: "Wisconsin",
      abbreviation: "WI",
      slug: "wisconsin",
      description: "Online boater education course approved by NASBLA. Wisconsin requires education for operators age 12+ born on or after January 1, 1989.",
      agencyName: "Wisconsin Department of Natural Resources",
      agencyAbbreviation: "WDNR",
      minimumAge: 12,
      fieldDayRequired: false,
      courseUrl: "https://dnr.wisconsin.gov/Education/OutdoorSkills/safetyEducation",
      importantNotes: "Required for operators age 12+ born on or after January 1, 1989.",
      isActive: true,
    },
    {
      name: "Wyoming",
      abbreviation: "WY",
      slug: "wyoming",
      description: "Wyoming has no mandatory boating safety education requirement, though voluntary courses are available.",
      agencyName: "Wyoming Game and Fish Department",
      agencyAbbreviation: "WGFD",
      fieldDayRequired: false,
      courseUrl: "https://wgfd.wyo.gov/fishing-boating/boating-watercraft",
      importantNotes: "No mandatory boating education requirement. Voluntary courses are available.",
      isActive: true,
    },
  ];

  await db.insert(states).values(stateData);

  const articleData = [
    {
      title: "What to Expect from Your Online Boater Education Course",
      slug: "what-to-expect-online-boater-education",
      excerpt: "A complete guide to what you'll learn in your online boater education course, from navigation rules to safe boat operation and water safety.",
      content: `<h2>Getting Started with Online Boater Education</h2>
<p>Online boater education courses are designed to teach you everything you need to know to become a safe and responsible boat operator. Whether you're a first-time boater or looking to get certified in a new state, here's what to expect.</p>

<h3>Course Topics</h3>
<p>Most state-approved online boater education courses cover these essential topics:</p>
<ul>
<li><strong>Navigation Rules</strong> - Learn the rules of the water, including right-of-way, proper signaling, and collision avoidance.</li>
<li><strong>Boat Operation</strong> - Understand how to safely operate different types of boats and manage vessel controls.</li>
<li><strong>Personal Flotation Devices (PFDs)</strong> - Learn why life jackets are essential and how to choose and wear them properly.</li>
<li><strong>Boating Laws and Regulations</strong> - Each state has specific rules about licensing, age requirements, and safety regulations.</li>
<li><strong>Water Safety</strong> - Weather awareness, emergency procedures, and what to do if someone falls overboard.</li>
<li><strong>Alcohol and Boating Laws</strong> - Understand the dangers of operating a vessel under the influence.</li>
</ul>

<h3>How Long Does It Take?</h3>
<p>Most online courses take between 3-4 hours to complete. The great thing about online courses is that you can work at your own pace and save your progress along the way.</p>

<h3>Practical Component Requirements</h3>
<p>Most boating safety courses are entirely online with no in-person practical component required. This makes it convenient to get certified quickly and easily.</p>

<h3>Getting Your Certificate</h3>
<p>Once you've completed the course, you'll receive your boater education certificate. This certificate is typically valid for life and is recognized by all 50 states under reciprocity agreements managed by NASBLA.</p>`,
      coverImageUrl: "/images/water-bg.png",
      isPublished: true,
      publishedAt: new Date("2025-12-15"),
    },
    {
      title: "Understanding Life Jackets and Personal Flotation Devices",
      slug: "life-jackets-pfd-guide",
      excerpt: "Life jackets are the most important piece of safety equipment for any boater. Learn why they save lives and how to choose the right PFD for your needs.",
      content: `<h2>Why Life Jackets Matter</h2>
<p>Personal Flotation Devices (PFDs), commonly known as life jackets, are the single most important safety tool for boaters. Statistics show that PFDs save lives every single day on America's waterways.</p>

<h3>Types of PFDs</h3>
<p>There are five different types of approved PFDs, each designed for different boating activities:</p>
<ul>
<li><strong>Type I</strong> - Offshore Life Jackets: Highest flotation, turns most unconscious wearers face-up in water</li>
<li><strong>Type II</strong> - Near-Shore Buoyant Vests: Good flotation, some turning capability</li>
<li><strong>Type III</strong> - Flotation Aids: Comfortable for extended wear, popular for recreational boating</li>
<li><strong>Type IV</strong> - Throwable Devices: Seat cushions and ring buoys, not meant to be worn</li>
<li><strong>Type V</strong> - Special Use Devices: Designed for specific water sports like wakeboarding</li>
</ul>

<h3>Choosing the Right PFD</h3>
<p>The best PFD is the one you'll actually wear. Consider comfort, fit, and the type of boating you'll be doing. Make sure your PFD is Coast Guard approved and is in good condition before every trip.</p>

<h3>Making PFDs a Habit</h3>
<p>Wear your PFD every time you're on the water, regardless of your swimming ability or how calm the conditions seem. Many boating accidents happen to experienced boaters who weren't wearing proper safety equipment.</p>`,
      isPublished: true,
      publishedAt: new Date("2026-01-10"),
    },
    {
      title: "Top 5 Tips for New Boaters",
      slug: "top-5-tips-new-boaters",
      excerpt: "Starting your boating journey? These five essential tips will help you prepare for a safe and enjoyable experience on the water.",
      content: `<h2>Essential Tips for New Boaters</h2>
<p>Boating is a wonderful outdoor recreational activity that connects you with family and friends. If you're just getting started, these tips will help set you up for success and safety on the water.</p>

<h3>1. Complete Your Boater Education First</h3>
<p>Before you head out on the water, make sure you've completed your state-required boater education course. This isn't just a legal requirement - it's genuinely valuable training that will make you a safer, more confident boat operator.</p>

<h3>2. Always Wear Your Life Jacket</h3>
<p>Make it a habit to wear your PFD every time you're on the water. It's the single most important safety device on your boat. Ensure everyone aboard, including children, has a properly fitting, Coast Guard-approved life jacket.</p>

<h3>3. Know the Rules of the Water</h3>
<p>Just like drivers follow traffic laws, boaters must follow Navigation Rules. Learn right-of-way situations, proper signaling, and how to communicate with other vessels. Understanding these rules prevents collisions and keeps everyone safe.</p>

<h3>4. Check Weather and Plan Your Route</h3>
<p>Always check the weather forecast before heading out. Be aware of water conditions, currents, and wind. File a float plan with someone on shore so they know where you're going and when to expect you back.</p>

<h3>5. Maintain Your Vessel and Equipment</h3>
<p>Regular maintenance keeps your boat running safely and reliably. Check fuel, water, and safety equipment before each trip. Keep your boat properly registered and documented, and familiarize yourself with all safety equipment aboard.</p>

<p>Remember, boating is about enjoying time on the water responsibly. Prioritize safety, and you'll create wonderful memories for years to come.</p>`,
      isPublished: true,
      publishedAt: new Date("2026-02-01"),
    },
  ];

  await db.insert(articles).values(articleData);

  console.log("Boater education database seeded successfully!");
}
